### ISSUE TITLE
Update instructions according new SDK version

### ISSUE THREAD

**Issue by kuruhuru** [d0sl/d0SDK#2]
New plugin's location, new examples etc

**Comment by DevilDimon** [comment]
I am getting multiple errors when trying to build examples in MPS 2018.3. What's the ETA on this issue?

**Comment by kuruhuru** [comment]
> I am getting multiple errors when trying to build examples in MPS 2018.3. What's the ETA on this issue?

Hello! 
Did you install d0sl plugin into MPS? Please, give a bit more info what you try.

Sincerely, Petr.

**Comment by DevilDimon** [comment]
I did the following steps:

**Comment by DevilDimon** [comment]
I did the following steps (following the quickstart tutorial):

1. Clone this repo
2. Install JetBrains MPS 2018.3.7 & the d0sl plugin
3. Open d0SDK directory in MPS
4. Build -> Rebuild Project in MPS

The model checker proceeds to find 327 issues: 310 errors, 11 infos & 6 warnings. The errors are mostly unresolved references. I cannot follow the quickstart tutorial further since the project has not been built successfully.

**Comment by kuruhuru** [comment]
можно по-русски, я думаю? :) лучше взять MPS последней версии. Плагин устанавливали из репозитория? в архиве zip?

**Comment by DevilDimon** [comment]
Если взять MPS 2019.3 и не мигрировать проект, как предлагается при запуске, то получается ошибка при попытке запустить ноду sandbox/ChessAll:
Error: Could not find or load main class org.d0sl.examples.sandbox.ChessAII
Caused by: java.lang.ClassNotFoundException: org.d0sl.examples.sandbox.ChessAII
Перед этим был сделан Rebuild Project.
Плагин устанавливал из репозитория, в архиве zip, версии 0.8.4 (в самом MPS отображается как 0.5).

**Comment by kuruhuru** [comment]
Проект надо мигрировать. Когда MPS меняет версию, они там многое могут менять в форматах синтаксического дерева. И чтобы старые проекты могли работать - запускается процедура миграции. Если миграция не помогает. Я сегодня-завтра проверю с нуля. У меня стоит версия 2019.1 еще не переходил на новую

**Comment by kuruhuru** [comment]
После тестов оказалось, что с новой версией 2019.3 SDK не работает (понадобится проапдейтить плагин под нее, это займет некоторое время). Но все работает с 2019.1 То есть пока можно ее скачать и использовать.

**Comment by DevilDimon** [comment]
Да, под 2019.1 все заработало

**Comment by kuruhuru** [comment]
Спасибо за терпение :) Если будут вопросы - я могу прокомментировать как и что устроено. например, по Скайпу, там можно экран расшарить.

**Comment by DevilDimon** [comment]
Да, напишите мне, можем созвониться на этой неделе. Мой логин devildimon1
